### ISSUE TITLE
Properly note when Public Install Page URL will, and when won't be generated (e.g. if compress=true)

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/steps-deploy-to-bitrise-io#12]
No Public Install Page URL will be generated for compressed files, nor in case it's not an APK or IPA file.

**Comment by godrei** [comment]
Hi @viktorbenei ,
we released a new version of Deploy to Bitrise.io step ([v1.3.0](https://github.com/bitrise-io/steps-deploy-to-bitrise-io/releases/tag/1.3.0)), this version will print a message if `is_enable_public_page` is set, but public download is not available for the given file type .

I'll close this issue, but if you need more info/help just let us know and we'll reopen it!
