### ISSUE TITLE
[Android] Version code and version names as environment variables

### ISSUE THREAD

**Issue by hijklmno** [bitrise-io/steps-deploy-to-bitrise-io#13]
Hi Bitrise,

I was wondering if it is possible to expose the version name and version code as an output variable? My goal is to publish a slack message with the version name and version code in the message itself, instead of needing to click the link each time.

Thanks!

**Comment by viktorbenei** [comment]
Hi,

Good idea, but it won't be implemented in this Step.

This step is not specific enough to be the right place for this feature - e.g. if you use a different deploy step you won't be able to get this information without deploying with this step too.

You can do this yourself with a Script step, using `aapt` https://github.com/bitrise-io/steps-deploy-to-bitrise-io/blob/master/uploaders/apk_uploader.rb#L47 / https://github.com/jamesmontemagno/steps-set-android-manifest-versions/blob/master/step.sh

You could either create a separate Step for this feature (first you should just solve it in a Script step, then we can help to transform the script into a Step if you want to), or request it in the Set Android Version step ( https://github.com/jamesmontemagno/steps-set-android-manifest-versions ).

**Comment by hijklmno** [comment]
Ok. I will follow up with a Script step.
