### ISSUE TITLE
Have a latest public install page

### ISSUE THREAD

**Issue by natinusala** [bitrise-io/steps-deploy-to-bitrise-io#14]
Would it be possible to have a latest public install page for a desired file ? That would be a page with a constant URL, which points to the install page of the latest successful build.

I'm currently thinking of using my own page which redirects to the latest install page URL,with a "Ping an URL with cURL" step for updating it. This way I can have a unique URL which leads to the latest build, but it's not very efficient.

Thanks !

**Comment by viktorbenei** [comment]
Great idea!

Please vote & comment on the related UserVoice feature requests:

* https://bitrise.uservoice.com/forums/235233-general/suggestions/11196141-static-public-install-page-so-that-qa-can-always
* https://bitrise.uservoice.com/forums/235233-general/suggestions/10577118-full-api
