### ISSUE TITLE
"No title found" as title in generated e-mail [Android]

### ISSUE THREAD

**Issue by VictorOjeda** [bitrise-io/steps-deploy-to-bitrise-io#19]
The title in the generated email is empty and I cannot find the right string to modify when making an Android build. The result is "No title found" as the title in the email (see attachment).

<img width="689" alt="screen shot 2016-06-27 at 7 36 00 pm" src="https://cloud.githubusercontent.com/assets/5543584/16402082/890815a0-3c9e-11e6-87bc-0d770876bbf1.png">

**Comment by viktorbenei** [comment]
Hi,

Please upgrade to the latest version of this step (Deploy to Bitrise.io - 1.2.4 - https://github.com/bitrise-io/steps-deploy-to-bitrise-io/releases/tag/1.2.4) that should fix the issue.

I'll close this ticket, but if you have this issue with the latest version please let us know and we'll reopen it!

**Comment by VictorOjeda** [comment]
Yes, it is fixed in version 1.2.4. 

Thank you.

**Comment by viktorbenei** [comment]
Thanks for reporting!
