### ISSUE TITLE
notify_user_groups without owner still notifies owner group

### ISSUE THREAD

**Issue by lhildenST** [bitrise-io/steps-deploy-to-bitrise-io#20]
I have a deploy-to-bitrise-io build step setup as follows to _**not**_ send emails to the owner, but the owner is still getting build email notifications:
```
    - deploy-to-bitrise-io@1.2.4:
        inputs:
        - notify_user_groups: testers, developers, admins
```
Is this a bug, or do I have my config setup incorrectly?

**Comment by viktorbenei** [comment]
The config seems to be good, we'll check what the issue can be. Thanks for reporting!

**Comment by godrei** [comment]
@lhildenST , are that emails build status emails or artifact generations email?

It looks like artifact generation emails (triggered by `deploy-to-bitrise-io` step) are sent to correct groups.

You can control build status emails on your app's settings page, but there you can not apply settings per groups...

**Comment by lhildenST** [comment]
@godrei The owner is receiving "Build [success] email"

**Comment by godrei** [comment]
this is a build status email and not triggered by this step. you can control this type of emails on app's settings page.

**Comment by lhildenST** [comment]
@godrei Makes sense, my misunderstanding.  Please remove the "bug" label on this issue then.  I will close.  

Note: I just gave 3 votes to https://bitrise.uservoice.com/forums/235233-general/suggestions/11650665-allow-per-user-notification-settings.
