### ISSUE TITLE
Error on upload - curl: (3) [globbing] bad range in column 80

### ISSUE THREAD

**Issue by gemmakbarlow-cidemo** [bitrise-io/steps-deploy-to-bitrise-io#24]
When attempting to upload an artifact built with an `.xcworkspace` scheme called 'Continuous Integration - Development [Project File]' I'm getting the following error in the 'Deploy to Bitrise' step.

```
-> Retrying...
curl: (3) [globbing] bad range in column 80
 (!) Upload failed
 (i) upload_url: {[REDACTED]}
Failed to upload the Artifact file
```

From [this issue](http://stackoverflow.com/questions/8333920/passing-a-url-with-brackets-to-curl), looks like it's the `[` character in the scheme name that's causing the problem. 

Seems like it can be fixed easily enough by passing an extra param to `curl`.

**Comment by viktorbenei** [comment]
Thanks for reporting the issue @gemmakbarlow-cidemo !

I added this to our internal bug tracker, a fix should be released soon ;)

**Comment by godrei** [comment]
Hi @gemmakbarlow-cidemo ,
new version [1.2.7](https://github.com/bitrise-io/steps-deploy-to-bitrise-io/releases/tag/1.2.7) is shared in the steplib, it will be available on the website in ~20mins.

I'll close this issue, but if you need more info/help just let us know and we'll reopen it!

**Comment by gemmakbarlow** [comment]
Fab, thanks @godrei.
