### ISSUE TITLE
Error installing unpacked APK file

### ISSUE THREAD

**Issue by priscila225** [bitrise-io/steps-deploy-to-bitrise-io#29]
Steps:

1. Add this step to compile a signed android build
2. After generated the build, download the deployed zip archive and unpack it
3. Try to install the signed apk.

Result on my device (Galaxy S7) : 
Failure [INSTALL_FAILED_INVALID_APK] message is displayed.
The logcat show this message: W/ (31953): Zip: 1 extraneous bytes at the end of the central directory

[temp fix] How I workaround this for now:
Instead use the ZipFileGenerator class, I use the bash command "zip -r" inside the ruby code

		# Create zip file using bash cmd
		zip_archive_path = tempfile.path + '.zip'
		command = "zip -r " + zip_archive_path + " " + path
		system "bash", "-c", command
		# Check if its ok
		raise "Failed to create compressed ZIP file" unless File.exists?(zip_archive_path)

Of course this is not the best solution. The 1 extra byte can be related of some function on zip_file_generator.rb

**Comment by viktorbenei** [comment]
Thank you @priscila225 , assigned this to the dev team, they'll look at it ASAP!

For context, this was the previous issue in the old artifact deployer step: https://github.com/bitrise-io/steps-bitrise-artifact-deploy/issues/2

**Comment by godrei** [comment]
Hi @priscila225 ,
we released a new version of Deploy to Bitrise.io step ([v1.3.0](https://github.com/bitrise-io/steps-deploy-to-bitrise-io/releases/tag/1.3.0)), this version fixes the zip issue.

Thanks again for the detailed report!

I'll close this issue, but if you need more info/help just let us know and we'll reopen it!
