### ISSUE TITLE
Allow me to specify the name of the compressed .zip file

### ISSUE THREAD

**Issue by lhildenST** [bitrise-io/steps-deploy-to-bitrise-io#42]
if I set `is_compress: true`, the build step deploys a file called `deploy.zip`.  I want to be able to specify the name of this file so that people who look at the deployment artifacts on the build page know what the .zip file contains.

**Comment by viktorbenei** [comment]
Great idea!

If you have the time feel free to send a PR! :)

(Added to our internal tracker, but probably won't have enough time in the near future)

**Comment by viktorbenei** [comment]
P.S.: feel free to post this to https://discuss.bitrise.io/c/feature-request for better visibility by others ;)

**Comment by godrei** [comment]
Hi @lhildenST ,
thanks for the feature request!
We released a new version ([1.3.7](https://github.com/bitrise-io/steps-deploy-to-bitrise-io/releases/tag/1.3.7)), use `zip_name` input to specify the the zip file's name.

I'll close this issue, but if you need more info/help just let us know and we'll reopen it!
