### ISSUE TITLE
Deploy failed, error: failed to get apk infos, output: AndroidManifest.xml:683: error: ERROR getting 'android:label' attribute: attribute value reference does not exist

### ISSUE THREAD

**Issue by Hesamedin** [bitrise-io/steps-deploy-to-bitrise-io#49]
Hi, I have integrated this step (v1.3.8) into my workflow and I am getting following error in this step:
```
Deploy failed, error: failed to get apk infos, output: AndroidManifest.xml:683: error: ERROR getting 'android:label' attribute: attribute value reference does not exist
```

However, I am able to install the .apk on emulator/device and there is no issue. I have even checked all `android:label` in all of my project's manifest but I didn't find any resource complain (resource does not exist).

So, it would be awesome if you can have a look at https://www.bitrise.io/build/7797e593bbc8db90

Thanks

**Comment by viktorbenei** [comment]
Hi @Hesamedin ,

Thanks for the bug report! :)

Did you try it with the previous version (1.3.7), did that have the same issue?

**Comment by Hesamedin** [comment]
Hi @viktorbenei, Thanks for your reply. Yes, I tried few lower version and I got similar error.
As, I am not able to find issue from my apk file then I decided to download generated apk file from Bitrise and send it via email. This is my script:

```
#!/bin/bash
# fail if any commands fails
# set -e
# debug log
set -x

cd $BITRISE_SOURCE_DIR
cd passenger-app/build/outputs/
zip -r apk.zip apk

# Send email
curl -s --user 'api:key-9b352d92cf92e897ccv3ae41622ede45' https://api.mailgun.net/v3/sandboxdoa85d8dr6f94f11865885ce556a31fa.mailgun.org/messages -F from='Mailgun Sandbox <my.email.1@gmail.com>' -F to='Hesam <my.email.2@gmail.com>' -F subject='APK file from Bitrise default workflow' -F text='apk file has been attached to this mail for your reference.' -F attachment=@apk.zip
```

However, this is what I got:
```
<html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

Is there any other way to download the apk file?

**Comment by Hesamedin** [comment]
Okay, I was able to get `FTP Upload` step into work and push my apk file somewhere and then download it.
I confirm I am able to install it on emulator/device without any issue and the app works fine.
I also confirm this problem doesn't happen always as some builds have passed without this problem (with similar workflow).

@viktorbenei what is the command you are using for analyzing apk files or how you analyze apk files? thanks.

**Comment by Hesamedin** [comment]
I checked your code at [here](https://github.com/bitrise-io/steps-deploy-to-bitrise-io/blob/master/uploaders/apkuploader.go#L74-L77). So, I am guessing you are running `aapt dump badging` on the apk file. Am I right? If yes, I found it doesn't work well alwys. There are some Q/A about it on Stackoverflow. [This is for refrense](https://stackoverflow.com/a/17009646/513413).

**Comment by viktorbenei** [comment]
Thanks for all the info and debugging @Hesamedin !

Could you please send us the APK which causes this issue? So far we could not reproduce this error, so it'd help a lot if we'd have an APK to test with. (feel free to send it via email/onsite chat if you don't want to share it here)

**Comment by Hesamedin** [comment]
Finally, we are able to find the issue. Luckily, there is no problem with `aapt` command.

We have localization for several countries. The problem was a developer had added a resource for a non-English language and (not the main one, English). Although problem fixed, the line of issue was not the line reported in `AndroidManifest.xml` by `aapt` command. So, heads up!

**Comment by viktorbenei** [comment]
Ahh, good catch & thanks for reporting the solution @Hesamedin ! :)
