### ISSUE TITLE
Deploy failed, error: failed to get apk infos, output: package: name='MYPACKAGENAME' versionCode='MYVERSIONCODE' versionName='MYVERSIONNAME' platformBuildVersionName='MYVERSIONNAME' compileSdkVersion='28' compileSdkVersionCodename='9'

### ISSUE THREAD

**Issue by taenguree** [bitrise-io/steps-deploy-to-bitrise-io#77]
I am getting following error on this step (v1.3.18)

`Deploy failed, error: failed to get apk infos, output: package: name='MYPACKAGENAME' versionCode='MYVERSIONCODE' versionName='MYVERSIONNAME' platformBuildVersionName='MYVERSIONNAME' compileSdkVersion='28' compileSdkVersionCodename='9'`

My project is an android project and it has many dimensions so it's variant is combinations of dimensions. for example fencyMyAppFree, classicMyAppPaid etc..

Are there any issues on this step with multi-dimension environment android project? 
and please leave the comment if I should provide more information about my build.

**Comment by bitce** [comment]
Hi @taenguree  initially can you please include a build URL so we can see into this issue?

**Comment by taenguree** [comment]
@bitce Hi, Thanks for the comment.

https://app.bitrise.io/build/439e8fa045aa1330

Here is the build URL.

**Comment by taenguree** [comment]
previously, my project has no [drawable] folder but has [drawable-xlarge] folder only. 
After I copied my android:icon resource from [drawable-xlarge] to [drawable] the issue had been fixed. 

Thanks !

**Comment by bitce** [comment]
Oh I see, thanks for clarifying, good job!
